# all available settings of specific linters
linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - diagnostic
      - style
      - experimental
      - opinionated
    disabled-checks:
      - hugeParam
      - rangeValCopy
      - unnamedResult
  gofmt:
    simplify: true
  errcheck:
    check-type-assertions: false
    check-blank: false
# options for analysis running
run:
  # which dirs to skip: they won't be analyzed;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but next dirs are always skipped independently
  # from this option's value:
  #   	vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs:
    - k8s
  # include test files
  tests: true
linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gocritic
    - gofmt
    - gosimple
    - misspell
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - varcheck
    - govet
