version: "3.9"

networks:
  api:
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16

services:
  db:
    container_name: wallet-db
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wallet
      PGDATA: /data/postgres
    volumes:
      - /var/wallet-api/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      api:
        ipv4_address: 172.23.0.101
    restart: unless-stopped

  migrations:
    container_name: wallet-migrations
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    entrypoint: /bin/bash ./entrypoint-migrations.sh
    networks:
      api:
        ipv4_address: 172.23.0.102
    depends_on:
      - db

  rest:
    container_name: wallet-rest
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    entrypoint: /bin/bash ./debug-rest.sh
    restart: always
    networks:
      api:
        ipv4_address: 172.23.0.103
    depends_on:
      - db
    ports:
      - "5001:5001"
      - "5000:5000"

  grpc:
    container_name: wallet-grpc
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    entrypoint: /bin/bash ./debug-grpc.sh
    restart: always
    networks:
      api:
        ipv4_address: 172.23.0.104
    depends_on:
      - db
    ports:
      - "4001:5001"
      - "4000:5000"
