// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IEndpoint is an autogenerated mock type for the IEndpoint type
type IEndpoint struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, request
func (_m *IEndpoint) Create(ctx context.Context, request interface{}) (interface{}, error) {
	ret := _m.Called(ctx, request)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) interface{}); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, interface{}) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, request
func (_m *IEndpoint) List(ctx context.Context, request interface{}) (interface{}, error) {
	ret := _m.Called(ctx, request)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) interface{}); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, interface{}) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIEndpoint interface {
	mock.TestingT
	Cleanup(func())
}

// NewIEndpoint creates a new instance of IEndpoint. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIEndpoint(t mockConstructorTestingTNewIEndpoint) *IEndpoint {
	mock := &IEndpoint{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
