// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	transaction "go-wallet-api/pkg/transaction"

	mock "github.com/stretchr/testify/mock"
)

// IService is an autogenerated mock type for the IService type
type IService struct {
	mock.Mock
}

// Create provides a mock function with given fields: req
func (_m *IService) Create(req transaction.CreateRequest) (transaction.ResponseDTO, error) {
	ret := _m.Called(req)

	var r0 transaction.ResponseDTO
	if rf, ok := ret.Get(0).(func(transaction.CreateRequest) transaction.ResponseDTO); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(transaction.ResponseDTO)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(transaction.CreateRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: req
func (_m *IService) List(req transaction.ListRequest) (transaction.ResponseListDTO, error) {
	ret := _m.Called(req)

	var r0 transaction.ResponseListDTO
	if rf, ok := ret.Get(0).(func(transaction.ListRequest) transaction.ResponseListDTO); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(transaction.ResponseListDTO)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(transaction.ListRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIService interface {
	mock.TestingT
	Cleanup(func())
}

// NewIService creates a new instance of IService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIService(t mockConstructorTestingTNewIService) *IService {
	mock := &IService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
