// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeAccountServiceServer is an autogenerated mock type for the UnsafeAccountServiceServer type
type UnsafeAccountServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedAccountServiceServer provides a mock function with given fields:
func (_m *UnsafeAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeAccountServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeAccountServiceServer creates a new instance of UnsafeAccountServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeAccountServiceServer(t mockConstructorTestingTNewUnsafeAccountServiceServer) *UnsafeAccountServiceServer {
	mock := &UnsafeAccountServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
